require("Scripts/Towns/Izlude/izlude")
require("Scripts/Towns/Veins/veins_npc")
require("Scripts/Towns/Veins/veins_ryu")
require("Scripts/Towns/Niflheim/divorce")
require("Scripts/Towns/Niflheim/Niflheim_1")